import type { NextPage } from "next";
import Head from "next/head";
import styled, { useTheme } from "styled-components";

function Home() {
  const theme = useTheme();
  console.log(theme);
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Wrapper>test</Wrapper>
    </div>
  );
}

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.primaryColor};
`;

export default Home;
