import type { NextPage } from "next";
import Head from "next/head";
import styled, { useTheme } from "styled-components";
import { useToggleTheme } from "../styles/theme";

const Home: NextPage = () => {
  const theme = useTheme();
  const { toggleTheme } = useToggleTheme();

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Wrapper>
        texttexttext
        <button onClick={() => toggleTheme()}>change theme</button>
      </Wrapper>
    </div>
  );
};

const Wrapper = styled.div`
  background-color: ${(props) => props.theme.backgroundColor};
`;

export default Home;
