import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { Theme, useTheme } from "../styles/theme";
import { styled } from "linaria/react";

function Home() {
  const { theme } = useTheme();
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Wrapper {...theme}>test</Wrapper>
    </div>
  );
}

const Wrapper = styled.div<Theme>`
  color: ${(props) => props.primaryColor};
`;

export default Home;
